export const filterConstants = {
    INITIALISE: "INITIALISE",
    SELECT_CATEGORY: "SELECT_CATEGORY",
    ALL_CATEGORY: "ALL_CATEGORY",
    CLEAR_ALL_FILTERS: "CLEAR_ALL_FILTERS",
    SORT: "SORT",
    SEARCH: "SEARCH",
};
